#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyKhoHang")]
	public partial class DBKhoHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPHIEUXUAT(PHIEUXUAT instance);
    partial void UpdatePHIEUXUAT(PHIEUXUAT instance);
    partial void DeletePHIEUXUAT(PHIEUXUAT instance);
    partial void InsertPHIEUNHAP(PHIEUNHAP instance);
    partial void UpdatePHIEUNHAP(PHIEUNHAP instance);
    partial void DeletePHIEUNHAP(PHIEUNHAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertLOAINHANVIEN(LOAINHANVIEN instance);
    partial void UpdateLOAINHANVIEN(LOAINHANVIEN instance);
    partial void DeleteLOAINHANVIEN(LOAINHANVIEN instance);
    partial void InsertHANGHOA(HANGHOA instance);
    partial void UpdateHANGHOA(HANGHOA instance);
    partial void DeleteHANGHOA(HANGHOA instance);
    partial void InsertCT_PHIEUXUAT(CT_PHIEUXUAT instance);
    partial void UpdateCT_PHIEUXUAT(CT_PHIEUXUAT instance);
    partial void DeleteCT_PHIEUXUAT(CT_PHIEUXUAT instance);
    partial void InsertCT_PHIEUNHAP(CT_PHIEUNHAP instance);
    partial void UpdateCT_PHIEUNHAP(CT_PHIEUNHAP instance);
    partial void DeleteCT_PHIEUNHAP(CT_PHIEUNHAP instance);
    #endregion
		
		public DBKhoHangDataContext() : 
				base(global::QuanLyKhoHang.Properties.Settings.Default.QuanLyKhoHangConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBKhoHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBKhoHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBKhoHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBKhoHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PHIEUXUAT> PHIEUXUATs
		{
			get
			{
				return this.GetTable<PHIEUXUAT>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this.GetTable<PHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<LOAINHANVIEN> LOAINHANVIENs
		{
			get
			{
				return this.GetTable<LOAINHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<HANGHOA> HANGHOAs
		{
			get
			{
				return this.GetTable<HANGHOA>();
			}
		}
		
		public System.Data.Linq.Table<CT_PHIEUXUAT> CT_PHIEUXUATs
		{
			get
			{
				return this.GetTable<CT_PHIEUXUAT>();
			}
		}
		
		public System.Data.Linq.Table<CT_PHIEUNHAP> CT_PHIEUNHAPs
		{
			get
			{
				return this.GetTable<CT_PHIEUNHAP>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUXUAT")]
	public partial class PHIEUXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_phieuxuat;
		
		private System.Nullable<System.DateTime> _ngayxuat;
		
		private System.Nullable<int> _id_nhanvien;
		
		private string _TenKH;
		
		private string _DiaChiKH;
		
		private string _SoDT;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phieuxuatChanging(int value);
    partial void Onid_phieuxuatChanged();
    partial void OnngayxuatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayxuatChanged();
    partial void Onid_nhanvienChanging(System.Nullable<int> value);
    partial void Onid_nhanvienChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiKHChanging(string value);
    partial void OnDiaChiKHChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    #endregion
		
		public PHIEUXUAT()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phieuxuat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_phieuxuat
		{
			get
			{
				return this._id_phieuxuat;
			}
			set
			{
				if ((this._id_phieuxuat != value))
				{
					this.Onid_phieuxuatChanging(value);
					this.SendPropertyChanging();
					this._id_phieuxuat = value;
					this.SendPropertyChanged("id_phieuxuat");
					this.Onid_phieuxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayxuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayxuat
		{
			get
			{
				return this._ngayxuat;
			}
			set
			{
				if ((this._ngayxuat != value))
				{
					this.OnngayxuatChanging(value);
					this.SendPropertyChanging();
					this._ngayxuat = value;
					this.SendPropertyChanged("ngayxuat");
					this.OnngayxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", DbType="Int")]
		public System.Nullable<int> id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKH", DbType="NVarChar(200)")]
		public string DiaChiKH
		{
			get
			{
				return this._DiaChiKH;
			}
			set
			{
				if ((this._DiaChiKH != value))
				{
					this.OnDiaChiKHChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKH = value;
					this.SendPropertyChanged("DiaChiKH");
					this.OnDiaChiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(50)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUXUAT", Storage="_NHANVIEN", ThisKey="id_nhanvien", OtherKey="id_nhanvien", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUXUATs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUXUATs.Add(this);
						this._id_nhanvien = value.id_nhanvien;
					}
					else
					{
						this._id_nhanvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAP")]
	public partial class PHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_phieunhap;
		
		private System.Nullable<System.DateTime> _ngaynhap;
		
		private System.Nullable<int> _id_nhacungcap;
		
		private System.Nullable<int> _id_nhanvien;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phieunhapChanging(int value);
    partial void Onid_phieunhapChanged();
    partial void OnngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhapChanged();
    partial void Onid_nhacungcapChanging(System.Nullable<int> value);
    partial void Onid_nhacungcapChanged();
    partial void Onid_nhanvienChanging(System.Nullable<int> value);
    partial void Onid_nhanvienChanged();
    #endregion
		
		public PHIEUNHAP()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phieunhap", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_phieunhap
		{
			get
			{
				return this._id_phieunhap;
			}
			set
			{
				if ((this._id_phieunhap != value))
				{
					this.Onid_phieunhapChanging(value);
					this.SendPropertyChanging();
					this._id_phieunhap = value;
					this.SendPropertyChanged("id_phieunhap");
					this.Onid_phieunhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhacungcap", DbType="Int")]
		public System.Nullable<int> id_nhacungcap
		{
			get
			{
				return this._id_nhacungcap;
			}
			set
			{
				if ((this._id_nhacungcap != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhacungcapChanging(value);
					this.SendPropertyChanging();
					this._id_nhacungcap = value;
					this.SendPropertyChanged("id_nhacungcap");
					this.Onid_nhacungcapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", DbType="Int")]
		public System.Nullable<int> id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAP", Storage="_NHANVIEN", ThisKey="id_nhanvien", OtherKey="id_nhanvien", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUNHAPs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPs.Add(this);
						this._id_nhanvien = value.id_nhanvien;
					}
					else
					{
						this._id_nhanvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAP", Storage="_NHACUNGCAP", ThisKey="id_nhacungcap", OtherKey="id_nhacungcap", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.PHIEUNHAPs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPs.Add(this);
						this._id_nhacungcap = value.id_nhacungcap;
					}
					else
					{
						this._id_nhacungcap = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nhanvien;
		
		private string _tennhanvien;
		
		private string _diachi;
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private System.Nullable<int> _id_loainv;
		
		private EntitySet<PHIEUXUAT> _PHIEUXUATs;
		
		private EntitySet<PHIEUNHAP> _PHIEUNHAPs;
		
		private EntityRef<LOAINHANVIEN> _LOAINHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhanvienChanging(int value);
    partial void Onid_nhanvienChanged();
    partial void OntennhanvienChanging(string value);
    partial void OntennhanvienChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void Onid_loainvChanging(System.Nullable<int> value);
    partial void Onid_loainvChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._PHIEUXUATs = new EntitySet<PHIEUXUAT>(new Action<PHIEUXUAT>(this.attach_PHIEUXUATs), new Action<PHIEUXUAT>(this.detach_PHIEUXUATs));
			this._PHIEUNHAPs = new EntitySet<PHIEUNHAP>(new Action<PHIEUNHAP>(this.attach_PHIEUNHAPs), new Action<PHIEUNHAP>(this.detach_PHIEUNHAPs));
			this._LOAINHANVIEN = default(EntityRef<LOAINHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(50)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this.OntennhanvienChanging(value);
					this.SendPropertyChanging();
					this._tennhanvien = value;
					this.SendPropertyChanged("tennhanvien");
					this.OntennhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(50)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loainv", DbType="Int")]
		public System.Nullable<int> id_loainv
		{
			get
			{
				return this._id_loainv;
			}
			set
			{
				if ((this._id_loainv != value))
				{
					if (this._LOAINHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_loainvChanging(value);
					this.SendPropertyChanging();
					this._id_loainv = value;
					this.SendPropertyChanged("id_loainv");
					this.Onid_loainvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUXUAT", Storage="_PHIEUXUATs", ThisKey="id_nhanvien", OtherKey="id_nhanvien")]
		public EntitySet<PHIEUXUAT> PHIEUXUATs
		{
			get
			{
				return this._PHIEUXUATs;
			}
			set
			{
				this._PHIEUXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUNHAP", Storage="_PHIEUNHAPs", ThisKey="id_nhanvien", OtherKey="id_nhanvien")]
		public EntitySet<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this._PHIEUNHAPs;
			}
			set
			{
				this._PHIEUNHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAINHANVIEN_NHANVIEN", Storage="_LOAINHANVIEN", ThisKey="id_loainv", OtherKey="id_loainv", IsForeignKey=true)]
		public LOAINHANVIEN LOAINHANVIEN
		{
			get
			{
				return this._LOAINHANVIEN.Entity;
			}
			set
			{
				LOAINHANVIEN previousValue = this._LOAINHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._LOAINHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAINHANVIEN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._LOAINHANVIEN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._id_loainv = value.id_loainv;
					}
					else
					{
						this._id_loainv = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAINHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUXUATs(PHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUXUATs(PHIEUXUAT entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nhacungcap;
		
		private string _tennhacungcap;
		
		private string _diachi;
		
		private EntitySet<PHIEUNHAP> _PHIEUNHAPs;
		
		private EntitySet<HANGHOA> _HANGHOAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhacungcapChanging(int value);
    partial void Onid_nhacungcapChanged();
    partial void OntennhacungcapChanging(string value);
    partial void OntennhacungcapChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._PHIEUNHAPs = new EntitySet<PHIEUNHAP>(new Action<PHIEUNHAP>(this.attach_PHIEUNHAPs), new Action<PHIEUNHAP>(this.detach_PHIEUNHAPs));
			this._HANGHOAs = new EntitySet<HANGHOA>(new Action<HANGHOA>(this.attach_HANGHOAs), new Action<HANGHOA>(this.detach_HANGHOAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhacungcap", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nhacungcap
		{
			get
			{
				return this._id_nhacungcap;
			}
			set
			{
				if ((this._id_nhacungcap != value))
				{
					this.Onid_nhacungcapChanging(value);
					this.SendPropertyChanging();
					this._id_nhacungcap = value;
					this.SendPropertyChanged("id_nhacungcap");
					this.Onid_nhacungcapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhacungcap", DbType="NVarChar(100)")]
		public string tennhacungcap
		{
			get
			{
				return this._tennhacungcap;
			}
			set
			{
				if ((this._tennhacungcap != value))
				{
					this.OntennhacungcapChanging(value);
					this.SendPropertyChanging();
					this._tennhacungcap = value;
					this.SendPropertyChanged("tennhacungcap");
					this.OntennhacungcapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(200)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUNHAP", Storage="_PHIEUNHAPs", ThisKey="id_nhacungcap", OtherKey="id_nhacungcap")]
		public EntitySet<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this._PHIEUNHAPs;
			}
			set
			{
				this._PHIEUNHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_HANGHOA", Storage="_HANGHOAs", ThisKey="id_nhacungcap", OtherKey="id_nhacungcap")]
		public EntitySet<HANGHOA> HANGHOAs
		{
			get
			{
				return this._HANGHOAs;
			}
			set
			{
				this._HANGHOAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_PHIEUNHAPs(PHIEUNHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
		
		private void attach_HANGHOAs(HANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_HANGHOAs(HANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAINHANVIEN")]
	public partial class LOAINHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_loainv;
		
		private string _tenloainv;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loainvChanging(int value);
    partial void Onid_loainvChanged();
    partial void OntenloainvChanging(string value);
    partial void OntenloainvChanged();
    #endregion
		
		public LOAINHANVIEN()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loainv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_loainv
		{
			get
			{
				return this._id_loainv;
			}
			set
			{
				if ((this._id_loainv != value))
				{
					this.Onid_loainvChanging(value);
					this.SendPropertyChanging();
					this._id_loainv = value;
					this.SendPropertyChanged("id_loainv");
					this.Onid_loainvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloainv", DbType="NVarChar(50)")]
		public string tenloainv
		{
			get
			{
				return this._tenloainv;
			}
			set
			{
				if ((this._tenloainv != value))
				{
					this.OntenloainvChanging(value);
					this.SendPropertyChanging();
					this._tenloainv = value;
					this.SendPropertyChanged("tenloainv");
					this.OntenloainvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAINHANVIEN_NHANVIEN", Storage="_NHANVIENs", ThisKey="id_loainv", OtherKey="id_loainv")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOAINHANVIEN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOAINHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANGHOA")]
	public partial class HANGHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hanghoa;
		
		private string _tenhanghoa;
		
		private string _donvitinh;
		
		private System.Nullable<int> _id_nhacungcap;
		
		private string _giaban;
		
		private System.Nullable<int> _soluongton;
		
		private string _mota;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hanghoaChanging(int value);
    partial void Onid_hanghoaChanged();
    partial void OntenhanghoaChanging(string value);
    partial void OntenhanghoaChanged();
    partial void OndonvitinhChanging(string value);
    partial void OndonvitinhChanged();
    partial void Onid_nhacungcapChanging(System.Nullable<int> value);
    partial void Onid_nhacungcapChanged();
    partial void OngiabanChanging(string value);
    partial void OngiabanChanged();
    partial void OnsoluongtonChanging(System.Nullable<int> value);
    partial void OnsoluongtonChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    #endregion
		
		public HANGHOA()
		{
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hanghoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_hanghoa
		{
			get
			{
				return this._id_hanghoa;
			}
			set
			{
				if ((this._id_hanghoa != value))
				{
					this.Onid_hanghoaChanging(value);
					this.SendPropertyChanging();
					this._id_hanghoa = value;
					this.SendPropertyChanged("id_hanghoa");
					this.Onid_hanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenhanghoa", DbType="NVarChar(50)")]
		public string tenhanghoa
		{
			get
			{
				return this._tenhanghoa;
			}
			set
			{
				if ((this._tenhanghoa != value))
				{
					this.OntenhanghoaChanging(value);
					this.SendPropertyChanging();
					this._tenhanghoa = value;
					this.SendPropertyChanged("tenhanghoa");
					this.OntenhanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donvitinh", DbType="NVarChar(30)")]
		public string donvitinh
		{
			get
			{
				return this._donvitinh;
			}
			set
			{
				if ((this._donvitinh != value))
				{
					this.OndonvitinhChanging(value);
					this.SendPropertyChanging();
					this._donvitinh = value;
					this.SendPropertyChanged("donvitinh");
					this.OndonvitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhacungcap", DbType="Int")]
		public System.Nullable<int> id_nhacungcap
		{
			get
			{
				return this._id_nhacungcap;
			}
			set
			{
				if ((this._id_nhacungcap != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhacungcapChanging(value);
					this.SendPropertyChanging();
					this._id_nhacungcap = value;
					this.SendPropertyChanged("id_nhacungcap");
					this.Onid_nhacungcapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaban", DbType="VarChar(50)")]
		public string giaban
		{
			get
			{
				return this._giaban;
			}
			set
			{
				if ((this._giaban != value))
				{
					this.OngiabanChanging(value);
					this.SendPropertyChanging();
					this._giaban = value;
					this.SendPropertyChanged("giaban");
					this.OngiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongton", DbType="Int")]
		public System.Nullable<int> soluongton
		{
			get
			{
				return this._soluongton;
			}
			set
			{
				if ((this._soluongton != value))
				{
					this.OnsoluongtonChanging(value);
					this.SendPropertyChanging();
					this._soluongton = value;
					this.SendPropertyChanged("soluongton");
					this.OnsoluongtonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(50)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_HANGHOA", Storage="_NHACUNGCAP", ThisKey="id_nhacungcap", OtherKey="id_nhacungcap", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.HANGHOAs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.HANGHOAs.Add(this);
						this._id_nhacungcap = value.id_nhacungcap;
					}
					else
					{
						this._id_nhacungcap = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PHIEUXUAT")]
	public partial class CT_PHIEUXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_phieuxuat;
		
		private int _id_hanghoa;
		
		private System.Nullable<int> _soluongxuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phieuxuatChanging(int value);
    partial void Onid_phieuxuatChanged();
    partial void Onid_hanghoaChanging(int value);
    partial void Onid_hanghoaChanged();
    partial void OnsoluongxuatChanging(System.Nullable<int> value);
    partial void OnsoluongxuatChanged();
    #endregion
		
		public CT_PHIEUXUAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phieuxuat", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_phieuxuat
		{
			get
			{
				return this._id_phieuxuat;
			}
			set
			{
				if ((this._id_phieuxuat != value))
				{
					this.Onid_phieuxuatChanging(value);
					this.SendPropertyChanging();
					this._id_phieuxuat = value;
					this.SendPropertyChanged("id_phieuxuat");
					this.Onid_phieuxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hanghoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_hanghoa
		{
			get
			{
				return this._id_hanghoa;
			}
			set
			{
				if ((this._id_hanghoa != value))
				{
					this.Onid_hanghoaChanging(value);
					this.SendPropertyChanging();
					this._id_hanghoa = value;
					this.SendPropertyChanged("id_hanghoa");
					this.Onid_hanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongxuat", DbType="Int")]
		public System.Nullable<int> soluongxuat
		{
			get
			{
				return this._soluongxuat;
			}
			set
			{
				if ((this._soluongxuat != value))
				{
					this.OnsoluongxuatChanging(value);
					this.SendPropertyChanging();
					this._soluongxuat = value;
					this.SendPropertyChanged("soluongxuat");
					this.OnsoluongxuatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PHIEUNHAP")]
	public partial class CT_PHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_phieunhap;
		
		private int _id_hanghoa;
		
		private System.Nullable<int> _soluongnhap;
		
		private System.Nullable<int> _gianhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phieunhapChanging(int value);
    partial void Onid_phieunhapChanged();
    partial void Onid_hanghoaChanging(int value);
    partial void Onid_hanghoaChanged();
    partial void OnsoluongnhapChanging(System.Nullable<int> value);
    partial void OnsoluongnhapChanged();
    partial void OngianhapChanging(System.Nullable<int> value);
    partial void OngianhapChanged();
    #endregion
		
		public CT_PHIEUNHAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phieunhap", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_phieunhap
		{
			get
			{
				return this._id_phieunhap;
			}
			set
			{
				if ((this._id_phieunhap != value))
				{
					this.Onid_phieunhapChanging(value);
					this.SendPropertyChanging();
					this._id_phieunhap = value;
					this.SendPropertyChanged("id_phieunhap");
					this.Onid_phieunhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hanghoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_hanghoa
		{
			get
			{
				return this._id_hanghoa;
			}
			set
			{
				if ((this._id_hanghoa != value))
				{
					this.Onid_hanghoaChanging(value);
					this.SendPropertyChanging();
					this._id_hanghoa = value;
					this.SendPropertyChanged("id_hanghoa");
					this.Onid_hanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongnhap", DbType="Int")]
		public System.Nullable<int> soluongnhap
		{
			get
			{
				return this._soluongnhap;
			}
			set
			{
				if ((this._soluongnhap != value))
				{
					this.OnsoluongnhapChanging(value);
					this.SendPropertyChanging();
					this._soluongnhap = value;
					this.SendPropertyChanged("soluongnhap");
					this.OnsoluongnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gianhap", DbType="Int")]
		public System.Nullable<int> gianhap
		{
			get
			{
				return this._gianhap;
			}
			set
			{
				if ((this._gianhap != value))
				{
					this.OngianhapChanging(value);
					this.SendPropertyChanging();
					this._gianhap = value;
					this.SendPropertyChanged("gianhap");
					this.OngianhapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
